import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import {useState} from 'react';
import Link from 'next/link';

function factorial(n, r = 1) {
  while (n > 0) r *= n--;
  return r;
}

function PrimeSolver() {
  var [grade, setGrade] = useState("")
  var [num, setNum] = useState("")
  return (
    <div>
    <br/>
     <TextField id="outlined-basic" onChange={(e)=>setNum(e.target.value)} label="Enter number" variant="outlined" fullWidth/>
     <br/><br/>
    <center><Button onClick={()=>setGrade(factorial(num))} variant="outlined">Calculate</Button></center>
    <br/>
    <br/>
    <br/>
    <center><b>The factorial is {grade}</b></center>
    </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Factorial
        </h1>

        <PrimeSolver/>
      </main>

      <footer className={styles.footer}>

          <p><Link href="/">Go home</Link></p>
 
      </footer>
    </div>
  )
}
