import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import {useState} from 'react';
import Link from 'next/link'
function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
function calcStuff(radius) {

var r = [
     parseFloat((2*radius).toFixed(2)),
    parseFloat((radius * radius * Math.PI).toFixed(2)),
  parseFloat((2 * Math.PI * radius).toFixed(2)),
]


  return r.map((e)=>numberWithCommas(e))
}


function CircleSolver() {
  var [data, setData] = useState([])
  var [num, setNum] = useState("")
  return (
    <div>
    <br/>
     <TextField id="outlined-basic" onChange={(e)=>setNum(e.target.value)} label="Enter radius" variant="outlined" fullWidth/>
     <br/><br/>
    <center><Button onClick={()=>setData(calcStuff(num))} variant="outlined">Calculate</Button></center>
    <br/>
    <br/>
    <br/>
    <center>
    
    The diameter is: <b>{data[0]}</b>
    <br/>
    The area is: <b>{data[1]}</b>
    <br/>
    The circumference is: <b>{data[2]}</b>

    </center>
    </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Circle
        </h1>

        <CircleSolver/>
      </main>

      <footer className={styles.footer}>

          <p><Link href="/">Go home</Link></p>
 
      </footer>
    </div>
  )
}
