import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <span style={{color: "blue"}}>school!</span>
        </h1>

        <p className={styles.description}>
          For students, made by students™ 
        </p>

        <div className={styles.grid}>
          <Link href="/grades" className={styles.card}>
          <div className={styles.card}>
            <h2>Grades &rarr;</h2>
            <p>Calculate a letter grade given your score. </p>
            </div>
          </Link>

          <Link href="/circles" className={styles.card}>
          <div className={styles.card} >
            <h2>Circles &rarr;</h2>
            <p>Quickly calculate area, circumference, and diameter of a circle!</p>
            </div>
          </Link>

          <Link
            href="/distance"
            className={styles.card}
          >
          <div className={styles.card} >
            <h2>Distance &rarr;</h2>
            <p>Determine how long it will take to travel between two locations given a rate and distance.</p>
             </div>
          </Link>

                    <Link
            href="/factorial"
            className={styles.card}
          >
          <div className={styles.card} >
            <h2>Factorial &rarr;</h2>
            <p>Find the factorial of a number! </p>
             </div>
          </Link>

                    <Link
            href="/prime"
            className={styles.card}
          >
          <div className={styles.card} >
            <h2>Prime &rarr;</h2>
            <p>Check if a number is prime!</p>
             </div>
          </Link>

        
        </div>
      </main>

      <footer className={styles.footer}>

          <p>Check out my <Link href="https://github.com/codergautam">Github!</Link></p>
 
      </footer>
    </div>
  )
}
