import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import {useState} from 'react';
import Grid from '@mui/material/Grid';
function numberWithCommas(x) {
    return x.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
}
function calcDistance([rate, dis]) {

    
    return numberWithCommas(parseFloat((dis/rate).toFixed(2)));
}
import Link from 'next/link'


function DistanceSolver() {
  var [distance, setDistance] = useState("")
  var [data, setData] = useState(["",""])
  return (
    <div>
    <br/>
    <Grid container spacing={2}>
        <Grid item xs={6}>
     <TextField id="outlined-basic" onChange={(e)=>{
            var dc = [...data]
            dc[0] = e.target.value
            setData(dc)
            }} label="Rate" variant="outlined" fullWidth/>

</Grid>
<Grid item xs={6}>
          <TextField id="outlined-basic" onChange={(e)=>{
            var dc = [...data]
            dc[1] = e.target.value
            setData(dc)
            }} label="Distance" variant="outlined" fullWidth/>
          </Grid>
          </Grid>
          <br/>
        
              

     <br/><br/>
    <center><Button onClick={()=>setDistance(calcDistance(data))} variant="outlined">Calculate</Button></center>
    <br/>
    <br/>
    <br/>
    <center>The time taken is: <b>{distance}</b></center>
    </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Distance
        </h1>

        <DistanceSolver/>
      </main>

      <footer className={styles.footer}>

          <p><Link href="/">Go home</Link></p>
 
      </footer>
    </div>
  )
}
