import Head from 'next/head'
import Image from 'next/image'
import styles from '../../styles/Home.module.css'
import TextField from '@mui/material/TextField';
import Button from '@mui/material/Button';
import {useState} from 'react';
import Link from 'next/link';

const isPrime = num => {
    for(let i = 2, s = Math.sqrt(num); i <= s; i++)
        if(num % i === 0) return false; 
    return num > 1;
}

function PrimeSolver() {
  var [grade, setGrade] = useState("")
  var [num, setNum] = useState("")
  return (
    <div>
    <br/>
     <TextField id="outlined-basic" onChange={(e)=>setNum(e.target.value)} label="Enter number" variant="outlined" fullWidth/>
     <br/><br/>
    <center><Button onClick={()=>setGrade(isPrime(num))} variant="outlined">Calculate</Button></center>
    <br/>
    <br/>
    <br/>
    <center><b>{grade?"The number is prime!" : "The number isn't prime!"}</b></center>
    </div>
  )
}

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>Will
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
         Prime
        </h1>

        <PrimeSolver/>
      </main>

      <footer className={styles.footer}>

          <p><Link href="/">Go home</Link></p>
 
      </footer>
    </div>
  )
}
